import http from 'node:http';
import {toWebRequest,sendWebResponse} from '@kujolang/commerce/runtime/node';
import {verifyDownstreamEvent} from '@kujolang/commerce';
import {authorized,json,required,stores,close} from './shared.mjs';

const port=Number(process.env.PORT||8788),origin=required('COMMERCE_CONSUMER_ORIGIN'),keys={[required('COMMERCE_SIGNING_KEY_ID')]:required('COMMERCE_SIGNING_SECRET')};if(process.env.COMMERCE_PREVIOUS_SIGNING_KEY_ID&&process.env.COMMERCE_PREVIOUS_SIGNING_SECRET)keys[process.env.COMMERCE_PREVIOUS_SIGNING_KEY_ID]=process.env.COMMERCE_PREVIOUS_SIGNING_SECRET;
const header=(headers,name)=>headers.get(name)||'';
const eventBody=async request=>{if(!(request.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))return{response:json({error:'Content-Type must be application/json'},415)};if(Number(request.headers.get('content-length')||0)>262144)return{response:json({error:'Request body too large'},413)};const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>262144)return{response:json({error:'Request body too large'},413)};try{return{event:JSON.parse(raw)};}catch{return{response:json({error:'Malformed JSON'},400)}};};
const handler=async request=>{const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/health')return json({ok:true});if(request.method==='POST'&&url.pathname==='/events'){const body=await eventBody(request);if(body.response)return body.response;const event=body.event;if(!await verifyDownstreamEvent({event,headers:request.headers},{keys,toleranceSeconds:300}))return json({error:'Invalid signature'},401);const fingerprint=[header(request.headers,'commerce-signature-key-id'),header(request.headers,'commerce-signature-timestamp'),header(request.headers,'commerce-signature')].join(':');const result=await stores.consumerStore.accept({fingerprint,event});return json(result,result.duplicate?200:202);}if(!authorized(request))return json({error:'Unauthorized'},401);if(request.method==='GET'&&url.pathname==='/operator/facts')return json({facts:await stores.consumerStore.list()});return json({error:'Not found'},404);};
const server=http.createServer(async(incoming,outgoing)=>{try{await sendWebResponse(await handler(await toWebRequest(incoming,{origin,maxBodyBytes:262144})),outgoing);}catch(error){console.error(JSON.stringify({level:'error',code:error.code==='REQUEST_BODY_TOO_LARGE'?'request_too_large':'consumer_failed'}));await sendWebResponse(json({error:error.code==='REQUEST_BODY_TOO_LARGE'?'Request body too large':'Request failed'},error.code==='REQUEST_BODY_TOO_LARGE'?413:500),outgoing);}}).listen(port,'0.0.0.0',()=>console.log(`Commerce consumer listening on ${port}`));
const shutdown=()=>server.close(async()=>{await close();process.exit(0);});process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
