import http from 'node:http';
import {toWebRequest,sendWebResponse} from '@kujolang/commerce/runtime/node';
import {durableWebhookHandler} from '@kujolang/commerce/runtime';
import {createReplayController} from '@kujolang/commerce';
import {authorized,json,publicReceipt,required,stores,close} from './shared.mjs';

const provider=process.env.COMMERCE_PROVIDER||'mock',port=Number(process.env.PORT||8787),publicOrigin=required('COMMERCE_PUBLIC_ORIGIN'),replay=createReplayController({deadLetters:stores.deadLetters,queue:stores.queue,audit:stores.audit});
const providerConfig=provider==='square'?{notification_url:required('SQUARE_NOTIFICATION_URL'),location_id:required('SQUARE_LOCATION_ID'),api_base:process.env.SQUARE_API_BASE||'https://connect.squareupsandbox.com',api_version:'2026-09-16'}:{};
const handler=async request=>{const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/health'){await stores.queue.list();return json({ok:true});}if(url.pathname==='/webhook')return durableWebhookHandler(request,{provider,secret:required('COMMERCE_WEBHOOK_SECRET'),config:providerConfig,env:process.env,ingress:stores.ingress,maxBodyBytes:1048576,archiveRaw:process.env.COMMERCE_ARCHIVE_RAW_EVENTS==='true'});if(!authorized(request))return json({error:'Unauthorized'},401);if(request.method==='GET'&&url.pathname==='/operator/state')return json({receipts:(await stores.receiptStore.list()).map(publicReceipt),jobs:await stores.queue.list(),dead_letters:await stores.deadLetters.list(),outbox:await stores.outbox.list(),drift:await stores.reconciliationStore.listFindings()});if(request.method==='POST'&&url.pathname.startsWith('/operator/replay/')){const id=decodeURIComponent(url.pathname.slice('/operator/replay/'.length));return json(await replay.replay(id,'operator'));}return json({error:'Not found'},404);};
const server=http.createServer(async(incoming,outgoing)=>{try{const request=await toWebRequest(incoming,{origin:publicOrigin,maxBodyBytes:1048576});await sendWebResponse(await handler(request),outgoing);}catch(error){console.error(JSON.stringify({level:'error',code:error.code==='REQUEST_BODY_TOO_LARGE'?'request_too_large':'request_failed'}));await sendWebResponse(json({error:error.code==='REQUEST_BODY_TOO_LARGE'?'Request body too large':'Request failed'},error.code==='REQUEST_BODY_TOO_LARGE'?413:500),outgoing);}}).listen(port,'0.0.0.0',()=>console.log(`Commerce receiver listening on ${port}`));
const shutdown=()=>server.close(async()=>{await close();process.exit(0);});process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
