import test from 'node:test';
import assert from 'node:assert/strict';
import {createConsentEvidence} from '../src/contracts.mjs';
import {createMemoryDeadLetterStore,createMemoryDurableQueue,createMemoryEventReceiptStore,createReplayController,processNext} from '../src/durability.mjs';
import {createMemoryIdempotencyStore,executeProviderOperation} from '../src/idempotency.mjs';
import {createMemoryOutbox,createMemoryReplayStore,deliverOutbox,signDownstreamEvent,verifyDownstreamEvent} from '../src/downstream.mjs';
import {convergeProviderState,createMemoryReconciliationStore,reconcileObject,reconcilePages} from '../src/reconciliation.mjs';
import {createMemoryRevisionStore,createOfferRevision} from '../src/revisions.mjs';
import {providerFor} from '../src/providers.mjs';
import {subscriptionHandler} from '../runtime/index.mjs';
import {durableWebhookHandler} from '../runtime/index.mjs';

const consent=()=>createConsentEvidence({id:'consent_1',customer_reference:'customer_1',checkout_reference:'checkout_1',offer_revision:'revision_1',amount:1200,currency:'USD',cadence:'monthly',purpose:'recurring subscription',consent_text_version:'consent-v1',terms_version:'terms-v1',occurred_at:'2026-09-19T12:00:00.000Z',payment_method_storage_authorized:true,recurring_authorized:true});

test('consent requires explicit saved-payment and recurring authorization',()=>{assert.equal(consent().recurring_authorized,true);assert.throws(()=>createConsentEvidence({...consent(),id:'consent_2',recurring_authorized:false}),/explicit/);});

test('offer revisions are deterministic and published values are immutable',async()=>{const input={sku:'monthly-plan',amount:1200,currency:'usd',cadence:'monthly',provider_mapping:{square:{plan_variation_id:'PLAN123'}}},a=await createOfferRevision(input,{published_at:'2026-01-01T00:00:00.000Z'}),b=await createOfferRevision({...input,provider_mapping:{square:{plan_variation_id:'PLAN123'}}},{published_at:'2026-01-02T00:00:00.000Z'});assert.equal(a.revision_id,b.revision_id);const store=createMemoryRevisionStore();await store.publish(a);const read=await store.get(a.revision_id);read.amount=1;assert.equal((await store.get(a.revision_id)).amount,1200);});

test('semantic idempotency persists intent and recovers an unknown provider outcome',async()=>{const store=createMemoryIdempotencyStore(),spec={operation_id:'op_1',type:'subscription.create',idempotency_key:'stable-key',intent:{sku:'monthly-plan'}};let mutations=0;await assert.rejects(()=>executeProviderOperation(spec,{store,mutate:async()=>{mutations+=1;throw new Error('connection lost');}}),/connection lost/);const result=await executeProviderOperation(spec,{store,mutate:async()=>{mutations+=1;return{id:'duplicate'};},recover:async record=>({id:'sub_recovered',key:record.idempotency_key})});assert.equal(result.id,'sub_recovered');assert.equal(mutations,1);assert.equal((await store.get('op_1')).state,'recovered');});

test('durable queue reclaims leases, retries, dead-letters, and replays',async()=>{let now=0;const receipts=createMemoryEventReceiptStore({now:()=>now,leaseMs:10}),queue=createMemoryDurableQueue({now:()=>now}),dead=createMemoryDeadLetterStore(),event={provider_event_id:'evt_1',provider:'mock'};assert.equal((await receipts.claim(event)).claimed,true);assert.equal((await receipts.claim(event)).claimed,false);now=11;assert.equal((await receipts.claim(event)).claimed,true);await queue.enqueue(event);let result=await processNext({queue,receipts,deadLetters:dead,maxAttempts:2,baseDelayMs:1,processor:async()=>{throw new Error('offline');}});assert.equal(result.status,'retrying');now=12;result=await processNext({queue,receipts,deadLetters:dead,maxAttempts:2,processor:async()=>{throw new Error('offline');}});assert.equal(result.status,'dead_lettered');const replay=createReplayController({deadLetters:dead,queue});assert.match((await replay.replay(result.job_id,'operator')).id,/^job_/);});

test('durable webhook acknowledges only after enqueue and suppresses duplicates',async()=>{const receipts=createMemoryEventReceiptStore(),queue=createMemoryDurableQueue(),payload=JSON.stringify({id:'evt_durable',type:'order.created',data:{id:'order_1'}}),invoke=()=>durableWebhookHandler(new Request('https://site.test/webhook',{method:'POST',headers:{'x-kujo-mock-signature':'secret'},body:payload}),{provider:'mock',secret:'secret',receiptStore:receipts,queue});assert.equal((await invoke()).status,202);assert.equal((await invoke()).status,200);assert.equal((await queue.list()).length,1);assert.equal((await receipts.get('evt_durable')).status,'queued');});

test('signed downstream events reject replay and support key lookup for rotation',async()=>{const input={event_id:'event_1',aggregate_id:'subscription_1',aggregate_version:2,type:'subscription.active',occurred_at:'2026-09-19T12:00:00.000Z',status:'active'},signed=await signDownstreamEvent(input,{key_id:'current',secret:'secret',now:()=>1000}),replays=createMemoryReplayStore(),options={keys:{previous:'old',current:'secret'},now:()=>1000,replayStore:replays};assert.equal(await verifyDownstreamEvent(signed,options),true);assert.equal(await verifyDownstreamEvent(signed,options),false);const outbox=createMemoryOutbox(),dead=createMemoryDeadLetterStore();await outbox.append(signed.event);let calls=0;assert.equal((await deliverOutbox({outbox,deadLetters:dead,publisher:{publish:async()=>{calls+=1;}}}))[0].status,'delivered');assert.equal(calls,1);});

test('downstream verification does not resolve inherited signing keys',async()=>{const input={event_id:'event_inherited',aggregate_id:'subscription_1',aggregate_version:3,type:'subscription.active',occurred_at:'2026-09-19T12:00:00.000Z',status:'active'},signed=await signDownstreamEvent(input,{key_id:'inherited',secret:'secret',now:()=>1000}),keys=Object.create({inherited:'secret'});assert.equal(await verifyDownstreamEvent(signed,{keys,now:()=>1000}),false);});

test('reconciliation ignores stale state and bounds pagination',async()=>{assert.equal(convergeProviderState({version:3,status:'active'},{version:2,status:'cancelled'}).status,'active');const store=createMemoryReconciliationStore(),adapter={capabilities:{direct_reconciliation:true},reconcileObject:async()=>({id:'sub',version:4,status:'paused'})};const result=await reconcileObject({providerAdapter:adapter,provider:'fixture',type:'subscription',id:'sub',local:{id:'sub',version:3,status:'active'},store});assert.equal(result.status,'drift');let pages=0;const summary=await reconcilePages({store,provider:'fixture',kind:'subscriptions',maxPages:2,listPage:async({cursor})=>{pages+=1;return{items:[{cursor}],next_cursor:`page_${pages}`};},process:async()=>{}});assert.equal(summary.truncated,true);assert.equal(summary.pages,2);});

test('state convergence is monotonic across deterministic event permutations',()=>{for(let current=0;current<20;current+=1)for(let incoming=0;incoming<20;incoming+=1){const result=convergeProviderState({version:current,status:`v${current}`},{version:incoming,status:`v${incoming}`});assert.equal(result.version,Math.max(current,incoming));}});

test('Square subscription workflow pins version, requires consent, and uses trusted mappings',async()=>{const square=providerFor('square'),calls=[],fetch=async(url,options={})=>{calls.push({url:String(url),options,body:options.body&&JSON.parse(options.body)});const path=new URL(url).pathname;if(path.endsWith('/customers/search'))return new Response(JSON.stringify({customers:[{id:'CUSTOMER1'}]}),{status:200});if(path.endsWith('/cards'))return new Response(JSON.stringify({card:{id:'ccof:card',customer_id:'CUSTOMER1',card_brand:'VISA',last_4:'1111'}}),{status:200,headers:{'x-request-id':'req_card'}});if(path.endsWith('/subscriptions'))return new Response(JSON.stringify({subscription:{id:'sub_1',status:'ACTIVE',version:1,customer_id:'CUSTOMER1',plan_variation_id:'PLAN123',created_at:'2026-09-19T12:00:00Z'}}),{status:200,headers:{'x-request-id':'req_sub'}});if(path.includes('/cancel')||path.includes('/pause')||path.includes('/resume'))return new Response(JSON.stringify({subscription:{id:'sub_1',status:'ACTIVE',version:2}}),{status:200});return new Response(JSON.stringify({subscription:{id:'sub_1',status:'ACTIVE',version:2},actions:[]}),{status:200});},config={location_id:'LABCDEFGHIJK',access_token_env:'TOKEN'},env={TOKEN:'fixture'},context={fetch,idempotencyKey:'operation-1',customerId:'CUSTOMER1',cardId:'ccof:card',consent:consent()};assert.equal((await square.findCustomer({email:'buyer@example.test'},config,env,{fetch})).id,'CUSTOMER1');const card=await square.createSavedPaymentMethod({source_id:'single-use-token',customer_id:'CUSTOMER1',consent:consent()},config,env,context);assert.equal(card.id,'ccof:card');const subscription=await square.createSubscription({type:'subscription',provider:{plan_variation_id:'PLAN123'}},config,env,context);assert.equal(subscription.id,'sub_1');await square.retrieveSubscription('sub_1',config,env,{fetch});await square.cancelSubscription('sub_1',config,env,{fetch});await square.pauseSubscription('sub_1',{},config,env,{fetch});await square.resumeSubscription('sub_1',{},config,env,{fetch});assert.ok(calls.every(call=>call.options.headers['square-version']==='2026-09-16'));assert.equal(calls.find(call=>call.url.endsWith('/subscriptions')).body.plan_variation_id,'PLAN123');assert.ok(!JSON.stringify(calls).includes('access_token'));});

test('Square rejects ambiguous customer matches',async()=>{const square=providerFor('square');await assert.rejects(()=>square.findCustomer({email:'buyer@example.test'},{location_id:'LABCDEFGHIJK'},{SQUARE_ACCESS_TOKEN:'fixture'},{fetch:async()=>new Response(JSON.stringify({customers:[{id:'1'},{id:'2'}]}),{status:200})}),/ambiguous/);});

test('subscription HTTP flow ignores browser price and provider identifiers',async()=>{const store=createMemoryIdempotencyStore(),catalog={provider:'square',products:[{sku:'monthly-plan',type:'subscription',availability:'available',price:{amount:1200,currency:'USD'},provider:{plan_variation_id:'TRUSTED_PLAN'}}]},calls=[];const request=new Request('https://site.test/subscription',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation_id:'operation_1',sku:'monthly-plan',amount:1,plan_variation_id:'ATTACKER_PLAN'})});const response=await subscriptionHandler(request,{catalog,config:{providers:{square:{location_id:'LABCDEFGHIJK',access_token_env:'TOKEN'}}},env:{TOKEN:'fixture'},idempotencyStore:store,resolveSubscriptionContext:async()=>({customerId:'CUSTOMER1',cardId:'ccof:card',consent:consent()}),fetch:async(_url,options)=>{calls.push(JSON.parse(options.body));return new Response(JSON.stringify({subscription:{id:'sub_1',status:'ACTIVE',version:1}}),{status:200});}});assert.equal(response.status,201);assert.equal(calls[0].plan_variation_id,'TRUSTED_PLAN');assert.equal(calls[0].price_override_money,undefined);});
