(()=>{'use strict';
const KEY='kujo:commerce:cart:v1',SCHEMA='kujo-cart/v1';let catalog;
const safe=raw=>{try{const v=JSON.parse(raw);return v?.schema===SCHEMA&&Array.isArray(v.items)?v:{schema:SCHEMA,items:[]}}catch{return{schema:SCHEMA,items:[]}}};
const get=()=>safe(localStorage.getItem(KEY));const save=c=>{localStorage.setItem(KEY,JSON.stringify(c));render();dispatchEvent(new CustomEvent('kujo:commerce:cart',{detail:c}))};
const product=sku=>catalog?.products.find(p=>p.sku===sku);
const api={getCart:get,getCartCount:()=>get().items.reduce((n,i)=>n+i.quantity,0),addToCart(sku,q=1){const p=product(sku);if(!p||p.availability!=='available')throw Error('Product is unavailable');const c=get(),i=c.items.find(x=>x.sku===sku),max=p.cart?.max||99;if(i)i.quantity=Math.min(max,i.quantity+q);else c.items.push({sku,quantity:Math.min(max,Math.max(1,q))});save(c)},removeFromCart(sku){const c=get();c.items=c.items.filter(i=>i.sku!==sku);save(c)},setQuantity(sku,q){const p=product(sku),c=get(),i=c.items.find(x=>x.sku===sku);if(!p||!i)return;if(q<1)return api.removeFromCart(sku);i.quantity=Math.min(p.cart?.max||99,Math.max(p.cart?.min||1,Number(q)||1));save(c)},incrementQuantity(s){const i=get().items.find(x=>x.sku===s);api.setQuantity(s,(i?.quantity||0)+1)},decrementQuantity(s){const i=get().items.find(x=>x.sku===s);api.setQuantity(s,(i?.quantity||1)-1)},clearCart(){save({schema:SCHEMA,items:[]})},async checkout(){const items=get().items;if(!items.length)throw Error('Your cart is empty');const r=await fetch('/_kujo/commerce/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items,checkout_attempt:crypto.randomUUID()})});const data=await r.json();if(!r.ok)throw Error(data.error||'Checkout failed');location.href=data.checkout_url}};
window.KujoCommerce=api;
function render(){document.querySelectorAll('[data-commerce-count]').forEach(e=>e.textContent=api.getCartCount());const root=document.querySelector('[data-commerce-cart]');if(!root||!catalog)return;const items=get().items.map(i=>({...i,product:product(i.sku)})).filter(i=>i.product);root.innerHTML=items.length?items.map(i=>`<article class="sk-card"><h2>${i.product.title}</h2><p>${i.product.price_display}</p><label>Quantity <input type="number" min="${i.product.cart?.min||1}" max="${i.product.cart?.max||99}" value="${i.quantity}" data-commerce-quantity="${i.sku}"></label><button type="button" data-commerce-remove="${i.sku}">Remove</button></article>`).join(''):'<p>Your cart is empty.</p>';}
document.addEventListener('click',async e=>{const add=e.target.closest('[data-commerce-add]'),remove=e.target.closest('[data-commerce-remove]'),clear=e.target.closest('[data-commerce-clear]'),checkout=e.target.closest('[data-commerce-checkout]');try{if(add){api.addToCart(add.dataset.commerceAdd);add.parentElement.querySelector('.commerce-status').textContent='Added to cart.'}if(remove)api.removeFromCart(remove.dataset.commerceRemove);if(clear)api.clearCart();if(checkout)await api.checkout()}catch(err){const out=document.querySelector('[data-commerce-error]');if(out)out.textContent=err.message}});
document.addEventListener('change',e=>{if(e.target.matches('[data-commerce-quantity]'))api.setQuantity(e.target.dataset.commerceQuantity,e.target.value)});
fetch('/_kujo/commerce/catalog.json').then(r=>{if(!r.ok)throw Error('catalog unavailable');return r.json()}).then(v=>{if(v.schema!=='kujo-commerce/v1')throw Error('unsupported catalog');catalog=v;render()}).catch(()=>{catalog={products:[]};render()});
})();
