import {CART_SCHEMA,CART_STORAGE_KEY,addItem,cartCount,emptyCart,parseCart,removeItem,setItemQuantity} from './cart-core.js';
let catalog;
const get=()=>parseCart(localStorage.getItem(CART_STORAGE_KEY));const updateCount=()=>document.querySelectorAll('[data-commerce-count]').forEach(e=>e.textContent=api.getCartCount());const save=(c,renderNow=true)=>{localStorage.setItem(CART_STORAGE_KEY,JSON.stringify(c));if(renderNow)render();else updateCount();dispatchEvent(new CustomEvent('kujo:commerce:cart',{detail:c}))};
const product=sku=>catalog?.products.find(p=>p.sku===sku);
const api={getCart:get,getCartCount:()=>cartCount(get()),addToCart(sku,q=1){const p=product(sku);if(!p||p.availability!=='available')throw Error('Product is unavailable');save(addItem(get(),sku,q,p.cart?.max||99))},removeFromCart(sku){save(removeItem(get(),sku))},setQuantity(sku,q,renderNow=true){const p=product(sku);if(!p)return;save(setItemQuantity(get(),sku,q,p.cart?.min||1,p.cart?.max||99),renderNow)},incrementQuantity(s){const i=get().items.find(x=>x.sku===s);api.setQuantity(s,(i?.quantity||0)+1)},decrementQuantity(s){const i=get().items.find(x=>x.sku===s);api.setQuantity(s,(i?.quantity||1)-1)},clearCart(){save(emptyCart())},async checkout(){const items=get().items;if(!items.length)throw Error('Your cart is empty');const r=await fetch('/_kujo/commerce/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items,checkout_attempt:crypto.randomUUID()})});const data=await r.json();if(!r.ok)throw Error(data.error||'Checkout failed');location.href=data.checkout_url}};
window.KujoCommerce=api;
function render(){updateCount();const root=document.querySelector('[data-commerce-cart]');if(!root||!catalog)return;const items=get().items.map(i=>({...i,product:product(i.sku)})).filter(i=>i.product);root.innerHTML=items.length?items.map(i=>`<article class="sk-card"><h2>${i.product.title}</h2><p>${i.product.price_display}</p><label>Quantity <input type="number" min="${i.product.cart?.min||1}" max="${i.product.cart?.max||99}" value="${i.quantity}" data-commerce-quantity="${i.sku}"></label><button type="button" data-commerce-remove="${i.sku}">Remove</button></article>`).join(''):'<p>Your cart is empty.</p>';}
function renderMockCheckout(){const root=document.querySelector('[data-commerce-mock-checkout]');if(!root||!catalog)return;const requested=new URLSearchParams(location.search).get('items')||'',items=requested.split(',').map(value=>{const [sku,rawQuantity]=value.split(':');return{product:product(sku),quantity:Number(rawQuantity)}}).filter(item=>item.product&&Number.isInteger(item.quantity)&&item.quantity>0);if(!items.length){root.textContent='No valid demo items were provided.';return}const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const summary=items.map(item=>`<li>${escape(item.product.title)} × ${item.quantity}</li>`).join(''),success=new URL(root.dataset.successUrl||'/checkout/success/',location.origin);success.searchParams.set('provider','mock');success.searchParams.set('items',requested);root.innerHTML=`<p><strong>Demo checkout — no real payment will be collected.</strong></p><ul>${summary}</ul><div class="actions"><a class="sk-button" href="${escape(success.toString())}">Confirm demo checkout</a><a class="sk-button sk-button--secondary" href="${escape(root.dataset.cancelUrl||'/checkout/cancel/')}">Cancel</a></div>`}
document.addEventListener('click',async e=>{const add=e.target.closest('[data-commerce-add]'),remove=e.target.closest('[data-commerce-remove]'),clear=e.target.closest('[data-commerce-clear]'),checkout=e.target.closest('[data-commerce-checkout]');try{if(add){api.addToCart(add.dataset.commerceAdd);add.parentElement.querySelector('.commerce-status').textContent='Added to cart.'}if(remove)api.removeFromCart(remove.dataset.commerceRemove);if(clear)api.clearCart();if(checkout)await api.checkout()}catch(err){const out=document.querySelector('[data-commerce-error]');if(out)out.textContent=err.message}});
document.addEventListener('input',e=>{if(e.target.matches('[data-commerce-quantity]'))api.setQuantity(e.target.dataset.commerceQuantity,e.target.value,false)});
fetch('/_kujo/commerce/catalog.json').then(r=>{if(!r.ok)throw Error('catalog unavailable');return r.json()}).then(v=>{if(v.schema!=='kujo-commerce/v1')throw Error('unsupported catalog');catalog=v;render();renderMockCheckout()}).catch(()=>{catalog={products:[]};render();renderMockCheckout()});
