import {CART_STORAGE_KEY,addItem,cartCount,emptyCart,parseCart,removeItem,setItemQuantity} from './cart-core.js';

let catalog={products:[],capabilities:{},cart:{enabled:true,multi_item:true}};
const element=(name,attributes={},text)=>{const node=document.createElement(name);for(const[key,value]of Object.entries(attributes)){if(value===false||value===undefined||value===null)continue;if(value===true)node.setAttribute(key,'');else node.setAttribute(key,String(value));}if(text!==undefined)node.textContent=String(text);return node;};
const get=()=>{try{return parseCart(localStorage.getItem(CART_STORAGE_KEY));}catch{return emptyCart();}};
const product=sku=>catalog.products.find(item=>item.sku===sku);
const availableItems=cart=>cart.items.filter(item=>{const value=product(item.sku);return value&&value.availability==='available'&&value.cart?.enabled!==false;});
const updateCount=()=>document.querySelectorAll('[data-commerce-count]').forEach(node=>{node.textContent=String(api.getCartCount());});
const save=(cart,renderNow=true)=>{try{localStorage.setItem(CART_STORAGE_KEY,JSON.stringify(cart));}catch{}if(renderNow)render();else updateCount();dispatchEvent(new CustomEvent('kujo:commerce:cart',{detail:cart}));};

const api={
  getCatalog:()=>catalog,getCart:get,getCartCount:()=>cartCount(get()),
  addToCart(sku,quantity=1){const value=product(sku);if(!catalog.cart?.enabled||!value||value.availability!=='available'||value.cart?.enabled===false)throw new Error('Product is unavailable');const current=get();if(!catalog.cart?.multi_item&&current.items.length&&!current.items.some(item=>item.sku===sku))throw new Error(`${catalog.provider} supports one product per checkout`);const safeQuantity=catalog.capabilities?.quantity?quantity:1;save(addItem(current,sku,safeQuantity,value.cart?.max||1));},
  removeFromCart(sku){save(removeItem(get(),sku));},
  setQuantity(sku,quantity,renderNow=true){const value=product(sku);if(!value)return;if(!catalog.capabilities?.quantity&&Number(quantity)!==1)throw new Error('Quantity is not supported');save(setItemQuantity(get(),sku,quantity,value.cart?.min||1,value.cart?.max||1),renderNow);},
  clearCart(){save(emptyCart());},
  async checkout(){const items=availableItems(get());if(!items.length)throw new Error('Your cart is empty');const response=await fetch('/_kujo/commerce/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items,checkout_attempt:crypto.randomUUID()})});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data.error||'Checkout failed');const url=new URL(data.checkout_url,location.href);if(!['https:','http:'].includes(url.protocol))throw new Error('Checkout returned an unsafe URL');location.assign(url.toString());}
};
window.KujoCommerce=api;

function cartItem(item){const value=product(item.sku),article=element('article',{'data-commerce-cart-item':item.sku}),heading=element('h2',{},value.variant_name?`${value.title} — ${value.variant_name}`:value.title);article.append(heading,element('p',{},value.price?.display||value.price_display));if(catalog.capabilities?.quantity&&value.cart?.quantity!==false&&value.cart?.max>1){const label=element('label',{},'Quantity '),input=element('input',{type:'number',min:value.cart?.min||1,max:value.cart?.max||99,value:item.quantity,'data-commerce-quantity':item.sku});label.append(input);article.append(label);}else article.append(element('p',{},`Quantity: ${item.quantity}`));article.append(element('button',{type:'button','data-commerce-remove':item.sku},'Remove'));return article;}

function render(){updateCount();for(const root of document.querySelectorAll('[data-commerce-cart], kujo-cart')){root.replaceChildren();const items=availableItems(get());if(!items.length){root.append(element('p',{},'Your cart is empty.'));continue;}items.forEach(item=>root.append(cartItem(item)));}}

function renderMockCheckout(){for(const root of document.querySelectorAll('[data-commerce-mock-checkout]')){root.replaceChildren();const requested=new URLSearchParams(location.search).get('items')||'',items=requested.split(',').map(value=>{const[sku,rawQuantity]=value.split(':');return{product:product(sku),quantity:Number(rawQuantity)};}).filter(item=>item.product&&Number.isInteger(item.quantity)&&item.quantity>0);if(!items.length){root.textContent='No valid demo items were provided.';continue;}const warning=element('p'),strong=element('strong',{},'Demo checkout — no real payment will be collected.');warning.append(strong);const list=element('ul');items.forEach(item=>list.append(element('li',{},`${item.product.title} × ${item.quantity}`)));const actions=element('div',{class:'commerce-actions'}),success=new URL(root.dataset.successUrl||'/checkout/success/',location.origin);success.searchParams.set('provider','mock');success.searchParams.set('items',requested);actions.append(element('a',{href:success.toString()},'Confirm demo checkout'),element('a',{href:new URL(root.dataset.cancelUrl||'/checkout/cancel/',location.origin).toString()},'Cancel'));root.append(warning,list,actions);}}

function updateVariant(select){const sku=select.value,value=product(sku),root=select.closest('[data-commerce-product], kujo-product');if(!value||!root)return;const price=root.querySelector('[data-commerce-price]'),button=root.querySelector('[data-commerce-add]');if(price)price.textContent=value.price?.display||value.price_display;if(button)button.dataset.commerceAdd=sku;}

class KujoBuyButton extends HTMLElement{connectedCallback(){if(this.querySelector('button'))return;const sku=this.getAttribute('sku'),button=element('button',{type:'button','data-commerce-add':sku},this.getAttribute('label')||'Add to cart');this.append(button);}}
class KujoCart extends HTMLElement{connectedCallback(){render();}}
class KujoProduct extends HTMLElement{connectedCallback(){const sku=this.getAttribute('sku'),value=product(sku);if(!value||this.childNodes.length)return;this.append(element('p',{},value.title),element('p',{'data-commerce-price':''},value.price?.display||value.price_display),element('button',{type:'button','data-commerce-add':sku},'Add to cart'));}}
if(globalThis.customElements){if(!customElements.get('kujo-buy-button'))customElements.define('kujo-buy-button',KujoBuyButton);if(!customElements.get('kujo-cart'))customElements.define('kujo-cart',KujoCart);if(!customElements.get('kujo-product'))customElements.define('kujo-product',KujoProduct);}

document.addEventListener('click',async event=>{const add=event.target.closest('[data-commerce-add]'),remove=event.target.closest('[data-commerce-remove]'),clear=event.target.closest('[data-commerce-clear]'),checkout=event.target.closest('[data-commerce-checkout]');try{if(add){api.addToCart(add.dataset.commerceAdd);const status=add.closest('[data-commerce-product], kujo-product')?.querySelector('.commerce-status');if(status)status.textContent='Added to cart.';}if(remove)api.removeFromCart(remove.dataset.commerceRemove);if(clear)api.clearCart();if(checkout)await api.checkout();}catch(failure){const output=document.querySelector('[data-commerce-error]');if(output)output.textContent=failure.message;}});
document.addEventListener('input',event=>{if(event.target.matches('[data-commerce-quantity]')){try{api.setQuantity(event.target.dataset.commerceQuantity,event.target.value,false);}catch{event.target.value='1';}}});
document.addEventListener('change',event=>{if(event.target.matches('[data-commerce-variant]'))updateVariant(event.target);});

fetch('/_kujo/commerce/catalog.json',{headers:{accept:'application/json'}}).then(response=>{if(!response.ok)throw new Error('catalog unavailable');return response.json();}).then(value=>{if(value.schema!=='kujo-commerce/v1'||!Array.isArray(value.products))throw new Error('unsupported catalog');catalog=value;document.querySelectorAll('[data-commerce-variant]').forEach(updateVariant);render();renderMockCheckout();}).catch(()=>{catalog={products:[],capabilities:{},cart:{enabled:false}};render();renderMockCheckout();});
