import { addIf, checkoutResult, fetchWithPolicy, form, hmacSha256, providerError, publicFields, safeUrl, timingSafeEqual } from '../provider-utils.mjs';
import { moneyDecimal, normalizeMoney } from '../money.mjs';

const caps = values => Object.freeze({
  hosted_checkout:false, dynamic_checkout:false, multi_item_checkout:false, quantity:false,
  one_time:false, subscriptions:false, digital_products:false, physical_products:false,
  services:false, shipping:false, inventory:false, discounts:false, promotion_codes:false,
  tax:false, customer_portal:false, webhooks:false, refund_events:false, entitlements:false,
  variants:false, localized_checkout:false, merchant_of_record:false,
  saved_payment_methods:false,trials:false,multiple_phases:false,static_recurring_prices:false,relative_recurring_prices:false,
  plan_changes:false,pause_resume:false,scheduled_cancellation:false,immediate_cancellation:false,disputes:false,
  event_recovery:false,direct_reconciliation:false,...values
});

const event = (provider, input, typeMap, object = input.data?.object || input.data || input.resource || {}) => {
  const metadata = object.metadata || object.custom_data || input.meta?.custom_data || {};
  const skus = Array.isArray(metadata.skus) ? metadata.skus : Object.keys(metadata).filter(key => key.startsWith('sku_')).sort().map(key => metadata[key]).filter(Boolean);
  const rawTime = input.created || input.create_time || input.occurred_at || input.created_at || input.timestamp || Date.now();
  const timestamp = typeof rawTime === 'number' ? new Date(rawTime > 1e12 ? rawTime : rawTime * 1000) : new Date(rawTime);
  return {
    schema:'kujo-commerce-event/v1', event_version:1, provider,
    type:typeMap[input.type || input.event_type || input.meta?.event_name] || 'commerce.unknown',
    provider_event_id:String(input.id || input.event_id || input.meta?.event_id || ''),
    provider_object_id:String(object.id || input.data?.id || ''), skus,
    timestamp:Number.isNaN(timestamp.valueOf()) ? new Date().toISOString() : timestamp.toISOString()
  };
};

const base = (id, capabilities, overrides = {}) => ({
  id, version:'1.0.0', capabilities:caps(capabilities), environment:[],
  validateConfig:() => [], validateProduct:() => [], toPublicProduct:() => ({}),
  verifyRemote:async product => ({ sku:product.sku, source:product.source, status:'ok', message:`${id} configuration is locally valid.` }),
  completeCheckout:async () => { throw new Error(`${id} does not require server-side checkout completion`); },
  createCustomerPortal:async () => null,
  validateWebhookConfig:({secret}) => capabilities.webhooks&&!secret?['webhook secret is not configured']:[],
  verifyWebhook:async () => false,
  normalizeWebhookEvent:input => event(id, input, {}), ...overrides
});

const hostedOrDynamic = (settings, identifier) => {
  if (settings?.checkout_mode === 'hosted') return 'hosted';
  if (settings?.checkout_mode === 'dynamic') return 'dynamic';
  if (settings?.[identifier]) return 'dynamic';
  return settings?.url ? 'hosted' : 'dynamic';
};
const requiredUrl = (settings, field = 'url') => { try { safeUrl(settings?.[field]); return []; } catch { return [`${field} must be a credential-free HTTPS URL.`]; } };

export const mockProvider = base('mock', {
  hosted_checkout:true,dynamic_checkout:true,multi_item_checkout:true,quantity:true,one_time:true,subscriptions:true,digital_products:true,physical_products:true,services:true,shipping:true,discounts:true,promotion_codes:true,tax:true,customer_portal:true,webhooks:true,refund_events:true,variants:true
}, {
  environment:['MOCK_WEBHOOK_SECRET'],
  validateConfig:config => config?.enabled === false ? ['Mock provider is selected but providers.mock.enabled is false.'] : [],
  createCheckout:async (items, config) => { const url = new URL(safeUrl(config.checkout_url || config.success_url));url.searchParams.set('provider','mock');url.searchParams.set('items',items.map(item=>`${item.sku}:${item.quantity}`).join(','));return checkoutResult(url); },
  createCustomerPortal:async config => ({portal_url:safeUrl(config.portal_url || 'https://example.com/account/?mock=portal')}),
  verifyWebhook:async ({request,secret}) => Boolean(secret) && request.headers.get('x-kujo-mock-signature') === secret,
  normalizeWebhookEvent:input => event('mock',input,{'checkout.completed':'commerce.checkout.completed','order.created':'commerce.order.created','subscription.created':'commerce.subscription.created','refund.created':'commerce.refund.created'})
});

export const linkProvider = base('link', {hosted_checkout:true,one_time:true,subscriptions:true,digital_products:true,physical_products:true,services:true}, {
  validateProduct:(_product,settings)=>requiredUrl(settings), toPublicProduct:settings=>publicFields(settings,['url']),
  verifyRemote:async(product,_config,_env,context={})=>{const response=await fetchWithPolicy(product.providers.link.url,{method:'HEAD',redirect:'manual'},context);const ok=response.ok||[301,302,303,307,308].includes(response.status);return{sku:product.sku,source:product.source,status:ok?'ok':'error',message:`Hosted link returned HTTP ${response.status}.`};},
  createCheckout:async items=>{if(items.length!==1||items[0].quantity!==1)throw new Error('Link supports one product with quantity one per checkout');return checkoutResult(items[0].provider.url);}
});

const stripeEvents={'checkout.session.completed':'commerce.checkout.completed','customer.subscription.created':'commerce.subscription.created','customer.subscription.updated':'commerce.subscription.updated','customer.subscription.deleted':'commerce.subscription.cancelled','charge.refunded':'commerce.refund.created','refund.created':'commerce.refund.created','customer.updated':'commerce.customer.updated','invoice.payment_failed':'commerce.payment.failed'};
export const stripeProvider=base('stripe',{hosted_checkout:true,dynamic_checkout:true,multi_item_checkout:true,quantity:true,one_time:true,subscriptions:true,digital_products:true,physical_products:true,services:true,shipping:true,discounts:true,promotion_codes:true,tax:true,customer_portal:true,webhooks:true,refund_events:true,variants:true,localized_checkout:true},{
  environment:['STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'],
  validateProduct:(_product,settings)=>{const mode=hostedOrDynamic(settings,'price_id');if(settings?.checkout_mode&&!['hosted','dynamic'].includes(settings.checkout_mode))return['checkout_mode must be dynamic or hosted.'];if(mode==='hosted')return requiredUrl(settings);return/^price_[A-Za-z0-9_]+$/.test(settings?.price_id||'')?[]:['Dynamic Stripe checkout requires providers.stripe.price_id.'];},
  toPublicProduct:settings=>publicFields(settings,['price_id','url','checkout_mode']),
  verifyRemote:async(product,config,env,context={})=>{const settings=product.providers.stripe||{};if(hostedOrDynamic(settings,'price_id')==='hosted')return linkProvider.verifyRemote({...product,providers:{link:{url:settings.url}}},config,env,context);const key=env[config.secret_key_env||'STRIPE_SECRET_KEY'];if(!key)throw new Error(`Missing environment variable ${config.secret_key_env||'STRIPE_SECRET_KEY'}`);const response=await fetchWithPolicy(`https://api.stripe.com/v1/prices/${encodeURIComponent(settings.price_id)}?expand[]=product`,{headers:{authorization:`Basic ${btoa(`${key}:`)}`,'stripe-version':config.api_version||'2025-08-27.basil'}},context);if(!response.ok)throw providerError(response,`Stripe returned HTTP ${response.status}`);const remote=await response.json(),warnings=[],price=product.price||normalizeMoney({currency:product.currency,display:product.price_display},{legacyDisplay:product.price_display});if(remote.active===false||remote.product?.active===false)return{sku:product.sku,source:product.source,status:'error',message:'Stripe Price or Product is inactive.'};if(remote.currency&&String(remote.currency).toUpperCase()!==price.currency)warnings.push(`currency is ${String(remote.currency).toUpperCase()}, configured ${price.currency}`);if(Number.isInteger(remote.unit_amount)&&remote.unit_amount!==price.amount)warnings.push(`amount is ${remote.unit_amount}, configured ${price.amount} minor units`);return{sku:product.sku,source:product.source,status:warnings.length?'warning':'ok',message:warnings.length?`Stripe verification warning: ${warnings.join('; ')}.`:'Stripe Price and Product are active.'};},
  createCheckout:async(items,config,env,context={})=>{if(items.length===1&&hostedOrDynamic(items[0].provider,'price_id')==='hosted')return checkoutResult(items[0].provider.url);if(items.some(item=>hostedOrDynamic(item.provider,'price_id')!=='dynamic'))throw new Error('Stripe hosted links cannot be combined in a dynamic cart');const key=env[config.secret_key_env||'STRIPE_SECRET_KEY'];if(!key)throw new Error('Stripe secret key is not configured');const mode=items.some(item=>item.type==='subscription')?'subscription':'payment';if(mode==='subscription'&&items.some(item=>item.type!=='subscription'))throw new Error('Stripe cannot mix recurring and one-time Commerce items in this checkout contract');const entries=[['mode',mode],['success_url',config.success_url],['cancel_url',config.cancel_url]];addIf(entries,'automatic_tax[enabled]',config.automatic_tax===undefined?undefined:Boolean(config.automatic_tax));addIf(entries,'allow_promotion_codes',config.promotion_codes===undefined?undefined:Boolean(config.promotion_codes));addIf(entries,'billing_address_collection',config.billing_address_collection);addIf(entries,'phone_number_collection[enabled]',config.phone_collection===undefined?undefined:Boolean(config.phone_collection));if(mode==='payment')addIf(entries,'customer_creation',config.customer_creation);addIf(entries,'client_reference_id',context.checkoutAttempt);addIf(entries,'metadata[checkout_attempt]',context.checkoutAttempt);(config.allowed_shipping_countries||[]).forEach((country,index)=>entries.push([`shipping_address_collection[allowed_countries][${index}]`,country]));(config.shipping_rate_ids||[]).forEach((rate,index)=>entries.push([`shipping_options[${index}][shipping_rate]`,rate]));(config.custom_fields||[]).forEach((field,index)=>{addIf(entries,`custom_fields[${index}][key]`,field.key);addIf(entries,`custom_fields[${index}][label][type]`,'custom');addIf(entries,`custom_fields[${index}][label][custom]`,field.label);addIf(entries,`custom_fields[${index}][type]`,field.type||'text');addIf(entries,`custom_fields[${index}][optional]`,Boolean(field.optional));});items.forEach((item,index)=>entries.push([`line_items[${index}][price]`,item.provider.price_id],[`line_items[${index}][quantity]`,item.quantity],[`metadata[sku_${index}]`,item.sku]));const headers={authorization:`Basic ${btoa(`${key}:`)}`,'content-type':'application/x-www-form-urlencoded','stripe-version':config.api_version||'2025-08-27.basil'};if(context.checkoutAttempt)headers['idempotency-key']=`kujo-${context.checkoutAttempt}`;const response=await fetchWithPolicy('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers,body:form(entries)},context);if(!response.ok)throw providerError(response,'Stripe checkout request failed');return checkoutResult((await response.json()).url,{provider_request_id:response.headers.get('request-id')||undefined});},
  createCustomerPortal:async(config,env,context={})=>{if(config.portal_url)return{portal_url:safeUrl(config.portal_url)};if(!context.customerId)throw new Error('Stripe customer portal session requires a customer ID');const key=env[config.secret_key_env||'STRIPE_SECRET_KEY'];if(!key)throw new Error('Stripe secret key is not configured');const entries=[['customer',context.customerId]];addIf(entries,'return_url',config.return_url);const response=await fetchWithPolicy('https://api.stripe.com/v1/billing_portal/sessions',{method:'POST',headers:{authorization:`Basic ${btoa(`${key}:`)}`,'content-type':'application/x-www-form-urlencoded','stripe-version':config.api_version||'2025-08-27.basil'},body:form(entries)},context);if(!response.ok)throw providerError(response,'Stripe customer portal request failed');return{portal_url:safeUrl((await response.json()).url)};},
  verifyWebhook:async({raw,request,secret,tolerance=300})=>{const parts=(request.headers.get('stripe-signature')||'').split(',').map(value=>value.split('='));const timestamp=parts.find(([key])=>key==='t')?.[1],signatures=parts.filter(([key])=>key==='v1').map(([,value])=>value);if(!secret||!timestamp||!signatures.length||Math.abs(Date.now()/1000-Number(timestamp))>tolerance)return false;const expected=await hmacSha256(secret,`${timestamp}.${raw}`);return signatures.some(signature=>timingSafeEqual(signature,expected));},normalizeWebhookEvent:input=>event('stripe',input,stripeEvents)
});

const polarEvents={'checkout.updated':'commerce.checkout.completed','order.created':'commerce.order.created','subscription.created':'commerce.subscription.created','subscription.updated':'commerce.subscription.updated','subscription.canceled':'commerce.subscription.cancelled','subscription.revoked':'commerce.subscription.cancelled','refund.created':'commerce.refund.created','customer.updated':'commerce.customer.updated'};
export const polarProvider=base('polar',{hosted_checkout:true,dynamic_checkout:true,one_time:true,subscriptions:true,digital_products:true,services:true,discounts:true,promotion_codes:true,customer_portal:true,webhooks:true,refund_events:true,entitlements:true,variants:true,merchant_of_record:true},{
  environment:['POLAR_ACCESS_TOKEN','POLAR_WEBHOOK_SECRET'],
  validateProduct:(_product,settings)=>hostedOrDynamic(settings,'product_id')==='hosted'?requiredUrl(settings):(/^[A-Za-z0-9_-]{8,}$/.test(settings?.product_id||'')?[]:['Dynamic Polar checkout requires providers.polar.product_id.']),toPublicProduct:settings=>publicFields(settings,['product_id','url','checkout_mode']),
  verifyRemote:async(product,config,env,context={})=>{const settings=product.providers.polar||{};if(hostedOrDynamic(settings,'product_id')==='hosted')return linkProvider.verifyRemote({...product,providers:{link:{url:settings.url}}},config,env,context);const token=env[config.access_token_env||'POLAR_ACCESS_TOKEN'];if(!token)throw new Error(`Missing environment variable ${config.access_token_env||'POLAR_ACCESS_TOKEN'}`);const response=await fetchWithPolicy(`${config.api_base||'https://api.polar.sh/v1'}/products/${encodeURIComponent(settings.product_id)}`,{headers:{authorization:`Bearer ${token}`}},context);if(!response.ok)throw providerError(response,`Polar returned HTTP ${response.status}`);const remote=await response.json();if(remote.is_archived)return{sku:product.sku,source:product.source,status:'error',message:'Polar Product is archived.'};const currencies=(remote.prices||[]).map(price=>String(price.price_currency||price.currency||'').toUpperCase()).filter(Boolean);const warning=currencies.length&&!currencies.includes(product.price.currency);return{sku:product.sku,source:product.source,status:warning?'warning':'ok',message:warning?`Polar currencies ${currencies.join(', ')} do not include ${product.price.currency}.`:'Polar Product is active.'};},
  createCheckout:async(items,config,env,context={})=>{if(items.length!==1||items[0].quantity!==1)throw new Error('Polar supports one product with quantity one per checkout');if(hostedOrDynamic(items[0].provider,'product_id')==='hosted')return checkoutResult(items[0].provider.url);const token=env[config.access_token_env||'POLAR_ACCESS_TOKEN'];if(!token)throw new Error('Polar access token is not configured');const body={products:[items[0].provider.product_id],success_url:config.success_url,metadata:{skus:[items[0].sku],checkout_attempt:context.checkoutAttempt||undefined}};if(config.allow_discount_codes!==undefined)body.allow_discount_codes=Boolean(config.allow_discount_codes);if(config.require_billing_address!==undefined)body.require_billing_address=Boolean(config.require_billing_address);if(context.customerEmail)body.customer_email=context.customerEmail;const response=await fetchWithPolicy(`${config.api_base||'https://api.polar.sh/v1'}/checkouts/`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)},context);if(!response.ok)throw providerError(response,'Polar checkout request failed');return checkoutResult((await response.json()).url);},
  createCustomerPortal:async(config,env,context={})=>{if(config.portal_url)return{portal_url:safeUrl(config.portal_url)};if(!context.customerId)throw new Error('Polar customer portal session requires a customer ID');const token=env[config.access_token_env||'POLAR_ACCESS_TOKEN'];if(!token)throw new Error('Polar access token is not configured');const response=await fetchWithPolicy(`${config.api_base||'https://api.polar.sh/v1'}/customer-sessions/`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({customer_id:context.customerId})},context);if(!response.ok)throw providerError(response,'Polar customer portal request failed');return{portal_url:safeUrl((await response.json()).customer_portal_url)};},
  verifyWebhook:async({raw,request,secret,tolerance=300})=>{const id=request.headers.get('webhook-id'),timestamp=request.headers.get('webhook-timestamp'),signatures=(request.headers.get('webhook-signature')||'').split(' ').map(value=>value.replace(/^v1,/,'')).filter(Boolean);if(!secret||!id||!timestamp||!signatures.length||Math.abs(Date.now()/1000-Number(timestamp))>tolerance)return false;const keyBytes=secret.startsWith('whsec_')?Uint8Array.from(atob(secret.slice(6)),char=>char.charCodeAt(0)):new TextEncoder().encode(secret);const key=await crypto.subtle.importKey('raw',keyBytes,{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${id}.${timestamp}.${raw}`)));const expected=btoa(String.fromCharCode(...bytes));return signatures.some(signature=>timingSafeEqual(signature,expected));},normalizeWebhookEvent:input=>event('polar',input,polarEvents)
});

async function paypalToken(config,env,context){const client=env[config.client_id_env||'PAYPAL_CLIENT_ID'],secret=env[config.client_secret_env||'PAYPAL_CLIENT_SECRET'];if(!client||!secret)throw new Error('PayPal client credentials are not configured');const base=config.api_base||'https://api-m.sandbox.paypal.com';const response=await fetchWithPolicy(`${base}/v1/oauth2/token`,{method:'POST',headers:{authorization:`Basic ${btoa(`${client}:${secret}`)}`,'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'},context);if(!response.ok)throw providerError(response,'PayPal authentication failed');return{base,token:(await response.json()).access_token};}
const paypalEvents={'CHECKOUT.ORDER.APPROVED':'commerce.checkout.approved','CHECKOUT.ORDER.COMPLETED':'commerce.checkout.completed','PAYMENT.CAPTURE.COMPLETED':'commerce.order.created','PAYMENT.CAPTURE.REFUNDED':'commerce.refund.created','BILLING.SUBSCRIPTION.CREATED':'commerce.subscription.created','BILLING.SUBSCRIPTION.UPDATED':'commerce.subscription.updated','BILLING.SUBSCRIPTION.CANCELLED':'commerce.subscription.cancelled','PAYMENT.CAPTURE.DENIED':'commerce.payment.failed'};
export const paypalProvider=base('paypal',{hosted_checkout:true,dynamic_checkout:true,multi_item_checkout:true,quantity:true,one_time:true,subscriptions:true,digital_products:true,physical_products:true,services:true,shipping:true,webhooks:true,refund_events:true,variants:true,localized_checkout:true},{
  environment:['PAYPAL_CLIENT_ID','PAYPAL_CLIENT_SECRET'],
  validateConfig:config=>config?.api_base&&!/^https:\/\/api-m\.(sandbox\.)?paypal\.com\/?$/.test(config.api_base)?['api_base must be an official PayPal live or sandbox API origin.']:[],validateProduct:(product,settings)=>product.type==='subscription'?(/^P-[A-Z0-9]+$/.test(settings?.plan_id||'')?[]:['PayPal subscription products require plan_id.']):(/^[-A-Za-z0-9_.]{1,127}$/.test(settings?.item_id||product.sku)?[]:['PayPal item_id is invalid.']),toPublicProduct:settings=>publicFields(settings,['item_id','plan_id']),
  verifyRemote:async(product,config,env,context={})=>{if(product.type!=='subscription')return{sku:product.sku,source:product.source,status:'ok',message:'PayPal one-time item mapping is locally valid; totals remain server-authored.'};const auth=await paypalToken(config,env,context);const response=await fetchWithPolicy(`${auth.base}/v1/billing/plans/${encodeURIComponent(product.providers.paypal.plan_id)}`,{headers:{authorization:`Bearer ${auth.token}`}},context);if(!response.ok)throw providerError(response,`PayPal returned HTTP ${response.status}`);const remote=await response.json();return{sku:product.sku,source:product.source,status:remote.status==='ACTIVE'?'ok':'error',message:`PayPal plan status is ${remote.status}.`};},
  createCheckout:async(items,config,env,context={})=>{const auth=await paypalToken(config,env,context),subscription=items.some(item=>item.type==='subscription');if(subscription){if(items.length!==1||items[0].quantity!==1)throw new Error('PayPal subscriptions support one plan with quantity one');const response=await fetchWithPolicy(`${auth.base}/v1/billing/subscriptions`,{method:'POST',headers:{authorization:`Bearer ${auth.token}`,'content-type':'application/json','paypal-request-id':context.checkoutAttempt||crypto.randomUUID()},body:JSON.stringify({plan_id:items[0].provider.plan_id,custom_id:items[0].sku,application_context:{return_url:config.success_url,cancel_url:config.cancel_url,user_action:'SUBSCRIBE_NOW'}})},context);if(!response.ok)throw providerError(response,'PayPal subscription request failed');const value=await response.json(),approval=value.links?.find(link=>link.rel==='approve')?.href;return checkoutResult(approval,{provider_reference:value.id});}const currency=items[0].price.currency;if(items.some(item=>item.price.currency!==currency))throw new Error('PayPal checkout requires one currency');const total=items.reduce((sum,item)=>sum+item.price.amount*item.quantity,0);const body={intent:'CAPTURE',purchase_units:[{reference_id:context.checkoutAttempt||'kujo-commerce',amount:{currency_code:currency,value:moneyDecimal({amount:total,currency}),breakdown:{item_total:{currency_code:currency,value:moneyDecimal({amount:total,currency})}}},items:items.map(item=>({name:item.title.slice(0,127),sku:(item.provider.item_id||item.sku).slice(0,127),quantity:String(item.quantity),unit_amount:{currency_code:currency,value:moneyDecimal(item.price)}})),custom_id:items.map(item=>item.sku).join(',').slice(0,127)}],payment_source:{paypal:{experience_context:{return_url:config.return_url||config.success_url,cancel_url:config.cancel_url,user_action:'PAY_NOW'}}}};const response=await fetchWithPolicy(`${auth.base}/v2/checkout/orders`,{method:'POST',headers:{authorization:`Bearer ${auth.token}`,'content-type':'application/json','paypal-request-id':context.checkoutAttempt||crypto.randomUUID()},body:JSON.stringify(body)},context);if(!response.ok)throw providerError(response,'PayPal order request failed');const value=await response.json(),approval=value.links?.find(link=>['payer-action','approve'].includes(link.rel))?.href;return checkoutResult(approval,{provider_reference:value.id,completion_required:true});},
  completeCheckout:async(reference,config,env,context={})=>{if(!/^[A-Z0-9]{8,32}$/.test(reference))throw new Error('Invalid PayPal order reference');const auth=await paypalToken(config,env,context);const response=await fetchWithPolicy(`${auth.base}/v2/checkout/orders/${encodeURIComponent(reference)}/capture`,{method:'POST',headers:{authorization:`Bearer ${auth.token}`,'content-type':'application/json','paypal-request-id':context.checkoutAttempt||`capture-${reference}`},body:'{}'},context);if(!response.ok)throw providerError(response,'PayPal capture request failed');const value=await response.json();return{provider_reference:value.id,status:value.status};},
  validateWebhookConfig:({config,env})=>!config.webhook_id||!env[config.client_id_env||'PAYPAL_CLIENT_ID']||!env[config.client_secret_env||'PAYPAL_CLIENT_SECRET']?['PayPal webhook ID and API credentials are not configured']:[],
  verifyWebhook:async({raw,request,config,env,context={}})=>{if(!config.webhook_id)return false;const auth=await paypalToken(config,env,context),input=JSON.parse(raw);const body={auth_algo:request.headers.get('paypal-auth-algo'),cert_url:request.headers.get('paypal-cert-url'),transmission_id:request.headers.get('paypal-transmission-id'),transmission_sig:request.headers.get('paypal-transmission-sig'),transmission_time:request.headers.get('paypal-transmission-time'),webhook_id:config.webhook_id,webhook_event:input};const response=await fetchWithPolicy(`${auth.base}/v1/notifications/verify-webhook-signature`,{method:'POST',headers:{authorization:`Bearer ${auth.token}`,'content-type':'application/json'},body:JSON.stringify(body)},context);return response.ok&&(await response.json()).verification_status==='SUCCESS';},normalizeWebhookEvent:input=>event('paypal',input,paypalEvents)
});

const squareEvents={'payment.created':'commerce.order.created','payment.updated':'commerce.payment.updated','payment.updated.COMPLETED':'commerce.checkout.completed','order.created':'commerce.order.created','order.updated':'commerce.order.updated','refund.created':'commerce.refund.created','refund.updated':'commerce.refund.updated','subscription.created':'commerce.subscription.created','subscription.updated':'commerce.subscription.updated','invoice.payment_made':'commerce.payment.succeeded','invoice.scheduled_charge_failed':'commerce.payment.failed','dispute.created':'commerce.dispute.created','dispute.state_changed':'commerce.dispute.updated'};
const SQUARE_VERSION='2026-09-16';
const squareBase=config=>config.api_base||'https://connect.squareupsandbox.com';
const squareHeaders=(token,config)=>({authorization:`Bearer ${token}`,'content-type':'application/json','square-version':config.api_version||SQUARE_VERSION});
const squareToken=(config,env)=>{const token=env[config.access_token_env||'SQUARE_ACCESS_TOKEN'];if(!token)throw new Error('Square access token is not configured');return token;};
const squareRequest=async(path,options,config,env,context)=>{const response=await fetchWithPolicy(`${squareBase(config)}${path}`,{...options,headers:{...squareHeaders(squareToken(config,env),config),...(options?.headers||{})}},context);if(!response.ok)throw providerError(response,`Square request failed (${response.status})`);return response;};
const operationKey=value=>String(value||'').replace(/[^A-Za-z0-9_-]/g,'').slice(0,45);
const requiredOperationKey=value=>{const key=operationKey(value);if(!key)throw new Error('Square mutation requires a persisted semantic idempotency key');return key;};
const subscriptionObject=value=>({id:String(value.id),status:String(value.status||'UNKNOWN').toLowerCase(),version:Number(value.version||0),customer_id:value.customer_id,plan_variation_id:value.plan_variation_id,card_id:value.card_id||null,created_at:value.created_at,updated_at:value.updated_at||value.created_at,canceled_date:value.canceled_date||null,charged_through_date:value.charged_through_date||null});
export const squareProvider=base('square',{hosted_checkout:true,dynamic_checkout:true,multi_item_checkout:true,quantity:true,one_time:true,subscriptions:true,digital_products:true,physical_products:true,services:true,shipping:true,inventory:true,discounts:true,promotion_codes:true,tax:true,webhooks:true,refund_events:true,variants:true,localized_checkout:true,saved_payment_methods:true,static_recurring_prices:true,pause_resume:true,scheduled_cancellation:true,disputes:true,direct_reconciliation:true},{
  environment:['SQUARE_ACCESS_TOKEN','SQUARE_WEBHOOK_SIGNATURE_KEY'],
  validateConfig:config=>{const issues=[];if(!/^L[A-Z0-9]{10,}$/.test(config?.location_id||''))issues.push('Square requires providers.square.location_id.');if(config?.api_base&&!['https://connect.squareup.com','https://connect.squareupsandbox.com'].includes(String(config.api_base).replace(/\/$/,'')))issues.push('api_base must be an official Square production or sandbox origin.');if(config?.api_version&&config.api_version!==SQUARE_VERSION)issues.push(`api_version must be the tested Square version ${SQUARE_VERSION}.`);return issues;},
  validateProduct:(product,settings)=>{if(product.type==='subscription'){const issues=[];if(!/^[-A-Z0-9]{6,}$/.test(settings?.plan_variation_id||''))issues.push('Square subscriptions require plan_variation_id.');if(product.cadence!=='monthly')issues.push('Square subscription support currently requires cadence: monthly.');return issues;}return/^[-A-Z0-9]{6,}$/.test(settings?.catalog_object_id||'')?[]:['Square requires catalog_object_id for each purchasable item.'];},toPublicProduct:settings=>publicFields(settings,['catalog_object_id','plan_variation_id']),
  verifyRemote:async(product,config,env,context={})=>{const id=product.type==='subscription'?product.providers.square.plan_variation_id:product.providers.square.catalog_object_id;const response=await squareRequest(`/v2/catalog/object/${encodeURIComponent(id)}`,{},config,env,context);const remote=await response.json();return{sku:product.sku,source:product.source,status:remote.object?.is_deleted?'error':'ok',message:remote.object?.is_deleted?'Square catalog object is deleted.':'Square catalog object exists.'};},
  createCheckout:async(items,config,env,context={})=>{if(items.some(item=>item.type==='subscription'))throw new Error('Square subscriptions use createSubscription, not Payment Links');const body={idempotency_key:operationKey(context.checkoutAttempt)||crypto.randomUUID(),order:{location_id:config.location_id,line_items:items.map(item=>({catalog_object_id:item.provider.catalog_object_id,quantity:String(item.quantity)}))},checkout_options:{redirect_url:config.success_url,ask_for_shipping_address:Boolean(config.ask_for_shipping_address),enable_coupon:config.promotion_codes!==false}};const response=await squareRequest('/v2/online-checkout/payment-links',{method:'POST',body:JSON.stringify(body)},config,env,context);const value=await response.json();return checkoutResult(value.payment_link?.url,{provider_reference:value.payment_link?.id,provider_request_id:response.headers.get('x-request-id')||response.headers.get('x-square-request-id')||undefined});},
  findCustomer:async({email,reference_id},config,env,context={})=>{if(!email&&!reference_id)throw new Error('Square customer lookup requires email or reference_id');const filter=reference_id?{reference_id:{exact:reference_id}}:{email_address:{exact:email}};const response=await squareRequest('/v2/customers/search',{method:'POST',body:JSON.stringify({limit:3,query:{filter}})},config,env,context),customers=(await response.json()).customers||[];if(customers.length>1)throw Object.assign(new Error('Square customer lookup is ambiguous'),{code:'ambiguous_customer',terminal:true});return customers[0]||null;},
  createCustomer:async(customer,config,env,context={})=>{const body={idempotency_key:requiredOperationKey(context.idempotencyKey),email_address:customer.email_address,given_name:customer.given_name,family_name:customer.family_name,reference_id:customer.reference_id};const response=await squareRequest('/v2/customers',{method:'POST',body:JSON.stringify(body)},config,env,context);return(await response.json()).customer;},
  createSavedPaymentMethod:async({source_id,verification_token,customer_id,cardholder_name,billing_address,consent},config,env,context={})=>{if(!source_id||!customer_id)throw new Error('Square saved card requires a single-use source and customer');if(!consent?.payment_method_storage_authorized||!consent?.recurring_authorized)throw new Error('explicit saved-payment and recurring consent evidence is required');const body={idempotency_key:requiredOperationKey(context.idempotencyKey),source_id,verification_token,card:{customer_id,cardholder_name,billing_address}};const response=await squareRequest('/v2/cards',{method:'POST',body:JSON.stringify(body)},config,env,context);const card=(await response.json()).card;return{id:card.id,customer_id:card.customer_id,brand:card.card_brand,last_4:card.last_4,exp_month:card.exp_month,exp_year:card.exp_year,provider_request_id:response.headers.get('x-request-id')||undefined};},
  createSubscription:async(item,config,env,context={})=>{if(item.type!=='subscription'||!item.provider.plan_variation_id)throw new Error('trusted Square subscription mapping is required');if(!context.customerId)throw new Error('Square subscription requires a reconciled customer');if(!context.consent?.recurring_authorized)throw new Error('explicit recurring consent evidence is required');const body={idempotency_key:requiredOperationKey(context.idempotencyKey),location_id:config.location_id,plan_variation_id:item.provider.plan_variation_id,customer_id:context.customerId,card_id:context.cardId,start_date:context.startDate,source:{name:config.source_name||'Commerce Integration'}};const response=await squareRequest('/v2/subscriptions',{method:'POST',body:JSON.stringify(body)},config,env,context),value=await response.json();return{...subscriptionObject(value.subscription),provider_request_id:response.headers.get('x-request-id')||response.headers.get('x-square-request-id')||undefined};},
  retrieveSubscription:async(id,config,env,context={})=>{const response=await squareRequest(`/v2/subscriptions/${encodeURIComponent(id)}?include=actions`,{},config,env,context),value=await response.json();return{...subscriptionObject(value.subscription),actions:value.actions||[]};},
  cancelSubscription:async(id,config,env,context={})=>{const response=await squareRequest(`/v2/subscriptions/${encodeURIComponent(id)}/cancel`,{method:'POST',body:'{}'},config,env,context);return subscriptionObject((await response.json()).subscription);},
  pauseSubscription:async(id,input,config,env,context={})=>{const response=await squareRequest(`/v2/subscriptions/${encodeURIComponent(id)}/pause`,{method:'POST',body:JSON.stringify(input||{})},config,env,context);return subscriptionObject((await response.json()).subscription);},
  resumeSubscription:async(id,input,config,env,context={})=>{const response=await squareRequest(`/v2/subscriptions/${encodeURIComponent(id)}/resume`,{method:'POST',body:JSON.stringify(input||{})},config,env,context);return subscriptionObject((await response.json()).subscription);},
  reconcileObject:async({type,id},config,env,context={})=>{if(type!=='subscription')throw new Error('Square reconciliation currently supports subscriptions');return squareProvider.retrieveSubscription(id,config,env,context);},
  dashboardUrl:({type,id})=>type==='subscription'?`https://squareup.com/dashboard/subscriptions/${encodeURIComponent(id)}`:null,
  verifyWebhook:async({raw,request,secret,config})=>{if(!secret||!config.notification_url)return false;const expected=await hmacSha256(secret,`${config.notification_url}${raw}`,'base64');return timingSafeEqual(expected,request.headers.get('x-square-hmacsha256-signature'));},normalizeWebhookEvent:input=>{const object=input.data?.object||{},status=object.payment?.status,map={...squareEvents};if(status&&squareEvents[`${input.type}.${status}`])map[input.type]=squareEvents[`${input.type}.${status}`];return event('square',input,map,object.subscription||object.payment||object.refund||object.dispute||object);}
});

const paddleEvents={'transaction.completed':'commerce.checkout.completed','transaction.created':'commerce.order.created','subscription.created':'commerce.subscription.created','subscription.updated':'commerce.subscription.updated','subscription.canceled':'commerce.subscription.cancelled','adjustment.created':'commerce.refund.created','transaction.payment_failed':'commerce.payment.failed'};
export const paddleProvider=base('paddle',{hosted_checkout:true,dynamic_checkout:true,multi_item_checkout:true,quantity:true,one_time:true,subscriptions:true,digital_products:true,services:true,discounts:true,promotion_codes:true,tax:true,customer_portal:true,webhooks:true,refund_events:true,entitlements:true,variants:true,localized_checkout:true,merchant_of_record:true},{
  environment:['PADDLE_API_KEY','PADDLE_WEBHOOK_SECRET'],
  validateProduct:(_product,settings)=>/^pri_[a-z0-9]{26}$/.test(settings?.price_id||'')?[]:['Paddle requires a current pri_ price_id.'],toPublicProduct:settings=>publicFields(settings,['price_id']),
  verifyRemote:async(product,config,env,context={})=>{const key=env[config.api_key_env||'PADDLE_API_KEY'];if(!key)throw new Error('Paddle API key is not configured');const base=config.api_base||'https://sandbox-api.paddle.com';const response=await fetchWithPolicy(`${base}/prices/${encodeURIComponent(product.providers.paddle.price_id)}`,{headers:{authorization:`Bearer ${key}`,'paddle-version':config.api_version||'1'}},context);if(!response.ok)throw providerError(response,`Paddle returned HTTP ${response.status}`);const remote=(await response.json()).data;return{sku:product.sku,source:product.source,status:remote?.status==='active'?'ok':'error',message:`Paddle price status is ${remote?.status||'unknown'}.`};},
  createCheckout:async(items,config,env,context={})=>{const key=env[config.api_key_env||'PADDLE_API_KEY'];if(!key)throw new Error('Paddle API key is not configured');const base=config.api_base||'https://sandbox-api.paddle.com';const body={items:items.map(item=>({price_id:item.provider.price_id,quantity:item.quantity})),custom_data:{skus:items.map(item=>item.sku),checkout_attempt:context.checkoutAttempt||undefined},checkout:{url:config.checkout_url||config.success_url}};const response=await fetchWithPolicy(`${base}/transactions`,{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json','paddle-version':config.api_version||'1'},body:JSON.stringify(body)},context);if(!response.ok)throw providerError(response,'Paddle transaction request failed');const value=(await response.json()).data;return checkoutResult(value.checkout?.url,{provider_reference:value.id});},
  createCustomerPortal:async(config,env,context={})=>{if(config.portal_url)return{portal_url:safeUrl(config.portal_url)};if(!context.customerId)throw new Error('Paddle portal requires a customer ID');const key=env[config.api_key_env||'PADDLE_API_KEY'];if(!key)throw new Error('Paddle API key is not configured');const base=config.api_base||'https://sandbox-api.paddle.com';const response=await fetchWithPolicy(`${base}/customers/${encodeURIComponent(context.customerId)}/portal-sessions`,{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json','paddle-version':config.api_version||'1'},body:'{}'},context);if(!response.ok)throw providerError(response,'Paddle portal request failed');return{portal_url:safeUrl((await response.json()).data?.urls?.general?.overview)};},
  verifyWebhook:async({raw,request,secret,tolerance=5})=>{const parts=(request.headers.get('paddle-signature')||'').split(';').map(value=>value.split('='));const timestamp=parts.find(([key])=>key==='ts')?.[1],signatures=parts.filter(([key])=>key==='h1').map(([,value])=>value);if(!secret||!timestamp||!signatures.length||Math.abs(Date.now()/1000-Number(timestamp))>tolerance)return false;const expected=await hmacSha256(secret,`${timestamp}:${raw}`);return signatures.some(signature=>timingSafeEqual(signature,expected));},normalizeWebhookEvent:input=>event('paddle',input,paddleEvents,input.data||{})
});

const lemonEvents={'order_created':'commerce.order.created','order_refunded':'commerce.refund.created','subscription_created':'commerce.subscription.created','subscription_updated':'commerce.subscription.updated','subscription_cancelled':'commerce.subscription.cancelled','subscription_expired':'commerce.subscription.cancelled','subscription_payment_failed':'commerce.payment.failed'};
export const lemonSqueezyProvider=base('lemon-squeezy',{hosted_checkout:true,dynamic_checkout:true,one_time:true,subscriptions:true,digital_products:true,services:true,discounts:true,promotion_codes:true,tax:true,customer_portal:true,webhooks:true,refund_events:true,entitlements:true,variants:true,localized_checkout:true,merchant_of_record:true},{
  environment:['LEMON_SQUEEZY_API_KEY','LEMON_SQUEEZY_WEBHOOK_SECRET'],
  validateConfig:config=>/^\d+$/.test(String(config?.store_id||''))?[]:['Lemon Squeezy requires providers.lemon-squeezy.store_id.'],validateProduct:(_product,settings)=>/^\d+$/.test(String(settings?.variant_id||''))?[]:['Lemon Squeezy requires variant_id for each purchasable item.'],toPublicProduct:settings=>publicFields(settings,['variant_id']),
  verifyRemote:async(product,config,env,context={})=>{const key=env[config.api_key_env||'LEMON_SQUEEZY_API_KEY'];if(!key)throw new Error('Lemon Squeezy API key is not configured');const response=await fetchWithPolicy(`https://api.lemonsqueezy.com/v1/variants/${encodeURIComponent(product.providers['lemon-squeezy'].variant_id)}`,{headers:{authorization:`Bearer ${key}`,accept:'application/vnd.api+json'}},context);if(!response.ok)throw providerError(response,`Lemon Squeezy returned HTTP ${response.status}`);const remote=(await response.json()).data?.attributes;return{sku:product.sku,source:product.source,status:remote?.status==='published'?'ok':'error',message:`Lemon Squeezy variant status is ${remote?.status||'unknown'}.`};},
  createCheckout:async(items,config,env,context={})=>{if(items.length!==1)throw new Error('Lemon Squeezy supports one variant per checkout');const key=env[config.api_key_env||'LEMON_SQUEEZY_API_KEY'];if(!key)throw new Error('Lemon Squeezy API key is not configured');const item=items[0],body={data:{type:'checkouts',attributes:{checkout_data:{custom:{sku:item.sku,checkout_attempt:context.checkoutAttempt||''}},product_options:{redirect_url:config.success_url,enabled_variants:[Number(item.provider.variant_id)]},checkout_options:{embed:false,media:true,logo:true,desc:true,discount:config.promotion_codes!==false}},relationships:{store:{data:{type:'stores',id:String(config.store_id)}},variant:{data:{type:'variants',id:String(item.provider.variant_id)}}}}};const response=await fetchWithPolicy('https://api.lemonsqueezy.com/v1/checkouts',{method:'POST',headers:{authorization:`Bearer ${key}`,accept:'application/vnd.api+json','content-type':'application/vnd.api+json'},body:JSON.stringify(body)},context);if(!response.ok)throw providerError(response,'Lemon Squeezy checkout request failed');const value=(await response.json()).data;return checkoutResult(value.attributes?.url,{provider_reference:value.id});},
  createCustomerPortal:async(config,_env,context={})=>{const url=context.portalUrl||config.portal_url;if(!url)throw new Error('Lemon Squeezy portal URL must come from a verified customer/order record');return{portal_url:safeUrl(url)};},verifyWebhook:async({raw,request,secret})=>Boolean(secret)&&timingSafeEqual(await hmacSha256(secret,raw),request.headers.get('x-signature')),normalizeWebhookEvent:input=>event('lemon-squeezy',input,lemonEvents,input.data?.attributes||{})
});
