import {test,expect} from '@playwright/test';

test('cart is capability-aware, persistent, and XSS-safe',async({page})=>{await page.goto('/');await page.locator('kujo-buy-button button').click();await expect(page.locator('kujo-cart h2')).toHaveText('<img src=x onerror="window.pwned=1">');await expect(page.locator('kujo-cart img')).toHaveCount(0);await expect(page.locator('[data-commerce-quantity]')).toHaveValue('1');await page.locator('[data-commerce-quantity]').fill('2');await page.reload();await expect(page.locator('[data-commerce-quantity]')).toHaveValue('2');expect(await page.evaluate(()=>window.pwned)).toBeUndefined();await page.locator('[data-commerce-remove]').click();await expect(page.locator('kujo-cart')).toContainText('Your cart is empty.');});

test('variant selection, keyboard controls, status announcements, and clear are accessible',async({page})=>{await page.goto('/');const variant=page.getByLabel('Variant');await variant.selectOption('shirt-white');await expect(page.locator('[data-commerce-price]')).toHaveText('$22.00');await page.getByRole('button',{name:'Add shirt'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('status')).toHaveText('Added to cart.');await expect(page.locator('kujo-cart h2')).toHaveText('Shirt — White');await expect(page.getByLabel('Quantity')).toBeVisible();await page.getByRole('button',{name:'Clear'}).click();await expect(page.locator('kujo-cart')).toContainText('Your cart is empty.')});

test('checkout, portal, and PayPal-style return completion run end to end',async({page})=>{await page.goto('/');await page.locator('kujo-buy-button button').click();await page.getByRole('button',{name:'Checkout'}).click();await expect(page.getByRole('heading',{name:'done'})).toBeVisible();await page.goto('/');await page.getByRole('button',{name:'Account portal'}).click();await expect(page.getByRole('heading',{name:'portal'})).toBeVisible();await page.goto('/return?token=ORDER12345&checkout_attempt=attempt_1');await expect(page.locator('[data-commerce-complete]')).toHaveText('Payment completed.')});

test('successful Mock returns clear the demo cart',async({page})=>{await page.goto('/');await page.locator('kujo-buy-button button').click();await page.goto('/checkout/success/?provider=mock');await expect(page.locator('kujo-cart')).toContainText('Your cart is empty.')});

test('checkout failures are exposed through an assertive alert',async({page})=>{await page.route('**/_kujo/commerce/checkout',async route=>route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'Provider unavailable'})}));await page.goto('/');await page.locator('kujo-buy-button button').click();await page.getByRole('button',{name:'Checkout'}).click();await expect(page.getByRole('alert')).toHaveText('Provider unavailable')});
